version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/e-commercial_app
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - e-commercial_network

  postgres:
    image: postgres:latest
    container_name: postgres_e_commercial
    environment:
      POSTGRES_DB: e-commercial_app
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - e-commercial_network

  redis:
    image: redis:latest
    container_name: redis_e_commercial
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./users.acl:/etc/redis/users.acl
      - redis_data:/data
    networks:
      - e-commercial_network

networks:
  e-commercial_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
